### ISSUE TITLE
C4F logo obstructs most of the map on small displays

### ISSUE THREAD

**Issue by maciej** [codeforberlin/CodeForFreedom2014#1]
![photo 29 09 2014 11 48 07](https://cloud.githubusercontent.com/assets/9706/4439948/ba08c734-47be-11e4-9df1-2ad9e05e585f.png)

**Comment by johnjohndoe** [comment]
:+1: Will fix this if you are not faster ...

**Comment by maciej** [comment]
@johnjohndoe my front-end skills are almost non-existent. :/

**Comment by johnjohndoe** [comment]
@maciej Same same. Challenge accepted :facepunch:
