### ISSUE TITLE
Use topo- instead of geojson

### ISSUE THREAD

**Issue by k-nut** [codeforberlin/CodeForFreedom2014#2]
The geojson is way to big. We should switch and use leaflet-omnivore to parse the topojson.

**Comment by k-nut** [comment]
There seem to be problems with leaflet-omnivore and topojson. See https://github.com/mapbox/leaflet-omnivore/issues/47

**Comment by johnjohndoe** [comment]
@k-nut This [article on "Maps with Leaflet, TopoJSON & Chroma.js"](http://blog.webkid.io/maps-with-leaflet-and-topojson/) by @moklick might be helpful.

**Comment by meule** [comment]
@johnjohndoe that article is not helpful in this case
@k-nut did you solve the problem? I have the same

**Comment by johnjohndoe** [comment]
I actually did not take time to look into this. I am not aware that @k-nut did ...?

**Comment by k-nut** [comment]
@meule the [issue](https://github.com/mapbox/leaflet-omnivore/issues/47) in the mapbox repository remains open. Maybe you can ping them there and ask for a fix? I would be very much interested in that!

**Comment by meule** [comment]
@k-nut it's leaflet bug (mapbox lib is on top of leafleat)
You can solve it particulary with topojson --stitch-poles option

**Comment by k-nut** [comment]
Wonderful. Done and deployed!

**Comment by johnjohndoe** [comment]
For reference see commit 480b30770bc55b7b85bb7763d58322968b173185.
